{
 "title": "RecruitAIr - Dispatcher API",
 "description": "Dispatcher API Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Create Offer Latency",
   "type": "heatmap",
   "description": "Distribution over Time of the Request Time to create a Job Offer",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(create_job_offer_requests_time_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create Applicant Latency",
   "type": "heatmap",
   "description": "Distribution over time of the request time to create an applicant",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(create_applicants_requests_time_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Criteria Latency",
   "type": "heatmap",
   "description": "Distribution over Time of the Request time of getting the criteria of a job offer",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(get_criteria_requests_time_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Score Latency",
   "type": "heatmap",
   "description": "Distribution over Time of the Request Time of getting the score of an applicant for the criteria of a job",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "rate(get_applicant_scores_requests_time_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Offers",
   "type": "stat",
   "description": "Total Job Offers created through the API",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(job_offers_created_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Job Creations",
   "type": "stat",
   "description": "Number of Job Creation Requests that failed some way or another",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(create_job_offer_requests_errors_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applicants",
   "type": "stat",
   "description": "Total amount of Applicants created through the API",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(applicants_created_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Applicant Creations",
   "type": "stat",
   "description": "Total amount of Applicant Creation Requests that failed one way or another",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(create_applicants_requests_errors_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Criteria",
   "type": "stat",
   "description": "Total amount of criteria created through the API",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(extractor_criteria_computed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scores",
   "type": "stat",
   "description": "Total scores generated using the Evaluator Sytstem",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(evaluator_scores_computed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scores Updated",
   "type": "stat",
   "description": "Total times that a score was updated through the API",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(update_applicant_score_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offer Length",
   "type": "heatmap",
   "description": "Distribution over Time of the Length of Job Offers created through the API",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(create_job_offer_text_length_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CV Length",
   "type": "heatmap",
   "description": "Distribution over Time of Resume Length of Applicants created through the API",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "rate(applicant_cv_length_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Criteria per Offer",
   "type": "heatmap",
   "description": "Distribution over Time of the number of criteria items per Job Offer returned in get criteria requests to the API",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(get_criteria_returned_per_request_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Score Value",
   "type": "heatmap",
   "description": "Evolution of the score values as returned by any score-getting API endpoint",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "rate(applicant_score_values_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Criteria Extraction Latency",
   "type": "heatmap",
   "description": "Distribution of the Time since a Job Offer is created until its Criteria is extracted",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(extractor_time_since_schedule_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Applicant Evaluation Latency",
   "type": "heatmap",
   "description": "Time since an Applicant and a Criterion being added to the system to the evaluator having scored the Applicant",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "rate(evaluator_time_since_schedule_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Score Corrections",
   "type": "heatmap",
   "description": "Distribution of the corrections that users put in through the API",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "rate(update_applicant_score_value_difference_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}