"""empty message

Revision ID: f55297a43c54
Revises:
Create Date: 2025-11-28 10:00:27.753539

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f55297a43c54"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_offers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "DONE", name="jobofferstatus"), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_offers_id"), "job_offers", ["id"], unique=False)
    op.create_index(op.f("ix_job_offers_status"), "job_offers", ["status"], unique=False)
    op.create_table(
        "applicants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cv", sa.String(), nullable=False),
        sa.Column("offer_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["job_offers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_applicants_id"), "applicants", ["id"], unique=False)
    op.create_index(op.f("ix_applicants_offer_id"), "applicants", ["offer_id"], unique=False)
    op.create_table(
        "criteria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("offer_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["job_offers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_criteria_id"), "criteria", ["id"], unique=False)
    op.create_index(op.f("ix_criteria_offer_id"), "criteria", ["offer_id"], unique=False)
    op.create_table(
        "applicant_scores",
        sa.Column("criteria_id", sa.Integer(), nullable=False),
        sa.Column("applicant_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["applicants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["criteria_id"],
            ["criteria.id"],
        ),
        sa.PrimaryKeyConstraint("criteria_id", "applicant_id"),
    )
    op.create_index(op.f("ix_applicant_scores_applicant_id"), "applicant_scores", ["applicant_id"], unique=False)
    op.create_index(op.f("ix_applicant_scores_criteria_id"), "applicant_scores", ["criteria_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_applicant_scores_criteria_id"), table_name="applicant_scores")
    op.drop_index(op.f("ix_applicant_scores_applicant_id"), table_name="applicant_scores")
    op.drop_table("applicant_scores")
    op.drop_index(op.f("ix_criteria_offer_id"), table_name="criteria")
    op.drop_index(op.f("ix_criteria_id"), table_name="criteria")
    op.drop_table("criteria")
    op.drop_index(op.f("ix_applicants_offer_id"), table_name="applicants")
    op.drop_index(op.f("ix_applicants_id"), table_name="applicants")
    op.drop_table("applicants")
    op.drop_index(op.f("ix_job_offers_status"), table_name="job_offers")
    op.drop_index(op.f("ix_job_offers_id"), table_name="job_offers")
    op.drop_table("job_offers")
    # ### end Alembic commands ###
